### ISSUE TITLE
Not fully accesible dataset

### ISSUE THREAD

**Issue by honcharov-danylo** [nickyringland/nested_named_entities#1]
Hello! Thank you for making this dataset available. 
I tried to download it, and it looks like I have to download somewhere PTB corpus (downloading the "treebank" NLTK corpus didn't help, is it in different format?). Could you please kindly advise, where is it possible to get PTB corpus, which is compatible with your repo?
Thank you again.

**Comment by dainlp** [comment]
Hi, Thank you for your interest in our dataset.

Since LDC owns the copyright on the underlying text, the files we provide here are only annotations. You would need to obtain the Wall Street Journal (WSJ) collection of Penn Treebank (PTB) from LDC (https://catalog.ldc.upenn.edu/).

Once you get the PTB corpus, you can run recover_text.py, of which the --ptb argument is the folder containing all the wsj files.

**Comment by honcharov-danylo** [comment]
Thank you!

**Comment by thtb** [comment]
PTB dataset contains 2500 articles while NNE contains 2312 articles. 

There are in total 25 folders, and 2500 files in PTB
There are in total 25 folders, and 2312 files in NNE
Traceback (most recent call last):
  File "recover_text.py", line 62, in <module>
    with open(os.path.join(args["nne_without_text"], folder, filename)) as in_f:
FileNotFoundError: [Errno 2] No such file or directory: '../Resources/no-text/03/wsj_0395'

Should I first remove the 188 acticles in PTB?

**Comment by dainlp** [comment]
Thanks for letting us know this. I believe it is because we are using different releases of PTB.
My test output is:
dai031@alienware-ep:~/Desktop/nested_named_entities/ACL2019 Paper/Code$ python recover_text.py --ptb=/data/dai031/Corpora/PTB/**LDC95T7**/treebank2/combined/wsj/ --nne_without_text=../Resources/no-text --nne_with_text=../Resources/with-text
There are in total 25 folders, and 2312 files in PTB
There are in total 25 folders, and 2312 files in NNE

If you can let me know the LDC_Catalog_ID of your PTB data, I can check the differences.

**Comment by thtb** [comment]
https://catalog.ldc.upenn.edu/LDC99T42

**Comment by thtb** [comment]
Treebank3 of LDC99T42

**Comment by thtb** [comment]
Treebank2 is ok！！

**Comment by AAristotle** [comment]
Hello! I get a problem.
The error happened in line 20.
KeyError: "There is no item named 'LDC95T7_Penn_Treebank_2/combined/wsj/02/wsj_0264.mrg' in the archive"
There are in total 25 folders, and 2312 files in PTB
There are in total 25 folders, and 2312 files in NNE

Zipfile '/nltk_data/corpora/treebank.zip' does not contain 'LDC95T7_Penn_Treebank_2/combined/wsj/02/wsj_0264.mrg'

Could you tell me what I should do?

**Comment by dainlp** [comment]
Hi @AAristotle I may start from checking nltk version; can you create a new python environment; remove your previous nltk_data and install nltk==3.7

**Comment by AAristotle** [comment]
Thank you for your reply!
Yes! It worked! Thank you so much!
